//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAAP2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public string OrderDetail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Priority { get; set; }
        public decimal TotalAmount { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
